[tool.flake8]
exclude = "hand_object_detector"
ignore = "H,E501,E402,W503,F841"

[tool.isort] # not used for now
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ["py38", "py39"]
exclude = "hand_object_detector"

[tool.mypy]
python_version = 3.9
exclude = "hand_object_detector"
show_error_codes = true
warn_unused_ignores = false
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
       "rospy",
       "rostest",
       "rospkg",
       "cv_bridge",
       "sensor_msgs.msg",
       "geometry_msgs.msg",
       "jsk_recognition_msgs.msg",
       "jsk_topic_tools",
       "jsk_data",
       "torchvision",
       "model.*",
       "matplotlib.*"
]
ignore_missing_imports = true

